### ISSUE TITLE
bug on /historico command

### ISSUE THREAD

**Issue by thisames** [arthur-mts/perso-dos-amigos#3]
apparently the history command only works once. after we try more than once with a person who has already been, it returns empty

**Comment by PapelRasgado** [comment]
@thisames 
Thank you for reporting this issue. Could you please provide a minimal, reproducible example to help us better understand and address the problem?

**Comment by PapelRasgado** [comment]
Thank you for bringing this issue to our attention. The problem has been resolved in commit a2aeed661b25116aa5010ed0f7379ef8721e3d46. Please let us know if you encounter any further issues!

**Comment by thisames** [comment]
thanks, working now
